version: '2'
services:
  db:
    image: alpine
    ports:
      - "80:80"
      - "443:443"

  web:
    image: nginx
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - db
